"""empty message

Revision ID: 851d35e7baf1
Revises: c9a675d3eaa3
Create Date: 2022-12-20 09:46:39.528885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851d35e7baf1'
down_revision = 'c9a675d3eaa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_slug')
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_post_slug', ['slug'], unique=False)

    # ### end Alembic commands ###
